create table if not exists public.crossword_leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null default 'Guest' check (char_length(player_name) between 1 and 40),
  score integer not null check (score >= 0),
  puzzle_date date not null default current_date,
  puzzle_number text,
  puzzle_title text,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  user_agent text
);

alter table public.crossword_leaderboard
  add column if not exists puzzle_number text,
  add column if not exists puzzle_title text;

create index if not exists crossword_leaderboard_puzzle_score_idx
  on public.crossword_leaderboard (puzzle_date desc, score asc, completed_at asc);

alter table public.crossword_leaderboard enable row level security;

drop policy if exists "Crossword leaderboard is readable" on public.crossword_leaderboard;
create policy "Crossword leaderboard is readable"
  on public.crossword_leaderboard
  for select
  using (true);

drop policy if exists "Crossword leaderboard accepts scores" on public.crossword_leaderboard;
create policy "Crossword leaderboard accepts scores"
  on public.crossword_leaderboard
  for insert
  with check (score >= 0 and char_length(player_name) between 1 and 40);
