"use client";

import { useState } from "react";

interface BlogPost {
  id: number;
  title: string;
  excerpt: string;
  content: string;
  date: string;
}

const blogPosts: BlogPost[] = [
  {
    id: 13,
    title: "Sora 2 and the Dead Internet: Why AI Innovation Can't Come at the Cost of Human Creators",
    excerpt: "On the trajectory of AI-generated content and what it means for authentic human creativity",
    content: `I'm pro-AI. Let me be clear about that from the start. Tools like OpenAI's Sora 2—which just dropped on September 30th, 2025—are nothing short of remarkable. The ability to generate photorealistic videos with synchronized sound, dialogue, and physics that actually make sense? That's the kind of technological leap that changes entire industries overnight. They're calling it "the GPT-3.5 moment for video," and honestly, that's not hyperbole.

But here's where I have to pump the brakes.

We're careening toward what's known as the "Dead Internet Theory," and if we're not careful, AI tools like Sora 2 will accelerate us right off a cliff—taking real, human creators down with us.

**What is the Dead Internet Theory?**

The Dead Internet Theory posits that the internet is increasingly dominated by AI-generated content, bot traffic, and corporate algorithms—all at the expense of authentic human interaction. And it's not just conspiracy theorist fear-mongering anymore. The data backs it up:

• 49.6% of all internet traffic in 2024 came from bots (Imperva Bad Bot Report)
• Experts predict 90% of online content will be AI-generated by 2025—yes, this year
• Meta just announced plans to introduce AI autonomous accounts that will "exist on their platforms kind of in the same way that accounts do," complete with bios, profile pictures, and the ability to generate and share content

We're not talking about the future. We're talking about right now.

**Sora 2: A Case Study in the Paradox**

Sora 2 embodies everything I love and fear about AI. On one hand, it democratizes video creation in a way that was unimaginable even a year ago. Want to create a backflip on a paddleboard with accurate buoyancy physics? Done. Need a triple axel animated with Olympic-level precision? Easy. There's even a "Cameos" feature that lets you insert yourself into scenes after a quick one-time recording.

The app became the #1 photo and video app on iOS within 24 hours of launch. That's adoption at light speed.

But here's the dark side: within days, the platform was flooded with copyrighted characters—Mario, Pikachu, you name it. It's a legal nightmare, sure, but more importantly, it highlights a deeper issue: AI tools trained on the work of human creators are now being used to generate content that competes directly with those same creators.

And it's not just video. Research from Stanford found that when AI-generated art enters the market, there's an 88% increase in active sellers using AI—but a 23% drop in non-AI human artists. The math is brutal: more content, fewer real creators.

**The Long-Term Damage**

Here's what keeps me up at night: if we continue down this trajectory, we're not just disrupting the "content-for-money" business model—we're fundamentally devaluing human creativity itself.

Think about it: if 90% of the internet is AI-generated, what happens to trust? To authenticity? To the serendipity of discovering something made by a person with a unique perspective, lived experience, and creative vision?

We're already seeing the signs:
• Creators report feeling simultaneously "empowered and unsettled"—they can produce more than ever, but they're questioning what it even means to create anymore
• The internet is becoming homogenized, algorithmically optimized for engagement over originality
• Real artists are being priced out by infinite AI competitors who never sleep, never need payment, and can pump out thousands of variations in seconds

This isn't progress. It's a race to the bottom.

**Where Do We Go From Here?**

I'm not calling for a ban on AI tools. That's neither practical nor desirable. Sora 2 and tools like it have legitimate, transformative use cases. They can help small creators compete, enable rapid prototyping, and unlock creative possibilities we haven't even imagined yet.

But we need guardrails. We need to:

1. **Protect human creators economically.** If AI is trained on human work, there needs to be compensation and attribution systems in place.

2. **Preserve spaces for authenticity.** Platforms need to distinguish between AI and human-generated content—not to ban AI, but to give people the choice to engage with real humans when they want to.

3. **Regulate responsibly.** Copyright law needs to catch up. We can't have a wild west where AI can clone anyone's style, voice, or likeness without consent.

4. **Shift the narrative.** AI should be a tool that amplifies human creativity, not a replacement for it. The goal isn't to flood the internet with content—it's to elevate quality, originality, and human connection.

**The Bottom Line**

Sora 2 is incredible. AI is incredible. But if we let these tools run unchecked, we risk creating an internet that's technically advanced but spiritually dead—a place where nothing is real, nothing is trusted, and human creators are left on the sidelines.

I'm pro-AI. But I'm also pro-human. And I refuse to believe we can't have both.

The question is: will we choose to?`,
    date: "2025-10-03",
  },
  {
    id: 12,
    title: "Lessons from Sun Zhu",
    excerpt: "Don't say to much",
    content: `Because you don't have to. ;)`,
    date: "2025-04-17",
  },
  {
    id: 11,
    title: "Honor",
    excerpt: "truth matters, especially about yourself",
    content: `Honor and your reputation are among the most important non-tangible qualities about yourself
    that should be valued and cherished at all costs. 
    Because if the the truth doesn't matter than you aren't shit.
    And if you think you are the shit then you protect your honor.
    And therefore, you never lie.
    And what is in the past is in the past and you accept and embrace the truth

    So if you catch someone in a lie then you know they will do it again.
    
    Fool me once shame on you, fool me twice shame on me (for trusting you twice).
    Caught someone lying to me just now, shame on me.

    Make sure to make sure you are someone that matters
    and that your word means something.

    And if you do lie to someone, try to always clear it up. Even if it was a lie that had good intentions 
    or especially if it was to bait them. If you can protect anyone it should be yourself.`,
    date: "2025-04-16",
  },
  {
    id: 10,
    title: "Concise Guide to AI Agents",
    excerpt: "Key agentic AI concepts, use cases and considerations to drive ROI",
    content: `AI agents are programs that can perform tasks independently using ai. They can boost productivity by handling operations through data access enabled.
    They can be specialized and assembled to work in teams for different divisions, essentially automating workflows.
    This is benefical because it saves firms costs, while being able to ship products faster. 

    How Agents Work?
    1. Sensing: Defining the problem, gathering data
    2. Reasoning: Interpreting the data, context, and requirements to make the decision
    3. Planning: Developing plan of action to reach required goal
    4. Coordination: Making sure the plan is aligned with managers
    5. Acting: Execution
    6. Learning and adaptation: Assessing outcomes, incorperating feedback, refinement
    
    Tomorrow: RAG vector search retrieval tool deep dive`,
    date: "2025-04-10",
  },
  {
    id: 9,
    title: "Priorities",
    excerpt: "pebbles and sand",
    content: `I usually start my days putting in hard work with the plan I created the day (night) prior.
    I grind for around 4-5 hours on days where I don't have classes. 
    This could be anything really, learning new skills, working on passion projects, leetcode problems or just studying.
    Now that finals are coming up, I have been really working on my efficiency with balancing everything on my plate.
    Making sure I am getting enough rest, exercise, and diet because health is wealth.
    
    Whole time making sure I am staying consistent with my diet and lifting.
    I've been eating high protein, no carbs, lots of fruits and vegetables, no snacks or processed foods.
    I really feel like putting the pebbles in the jar first is important which is why I start off with the most mentally straining activities before moving onto the physcial stuff.
    That way I can get everything I want to do in the day done before I can choose what to do in my free time.
    NBA games are getting better, music, seeing friends, or just going on walks.

    Picked up stretching and yoga recently and I feel so much better.
    Going to start working on my posture this week.`,
    date: "2025-04-09",
  },
  {
    id: 8,
    title: "On the Greats",
    excerpt: "Lebron",
    content: `Becoming great is hard, it requires more than just discipline and consistency.
    
It requires competitiveness. You have to wake up every day and keep going no matter how far you've come or how far ahead of the competition you are.
Lebron is the undisputed great but he’s still grinding daily to make it unanimous — why aren't you??`,
    date: "2025-04-06",
  },
  {
    id: 7,
    title: "Growth and Consistency",
    excerpt: "working hard",
    content: `Consistency is key to growth; with consistency, you need discipline and the right mindset. 
Always think positive.

Change what you can change, ignore what you can't.
Closed mouths do not get fed. Opportunities do not fall off trees.
Stay hungry, stay focused, stay active.

Going to try to become consistent with these blog posts to help keep myself accountable.`,
    date: "2025-04-08",
  },
  {
    id: 6,
    title: "AI Agents",
    excerpt: "automating my workflow",
    content: `Working on creating an organization that automates everything I can to maximize efficiency.
That way I can work when I am not at my computer—or even sleeping?`,
    date: "2025-04-07",
  },
  {
    id: 5,
    title: "Inspiration to the Hackathon Project",
    excerpt: "Why I Built the Healthcare Chatbot",
    content: `When I was in middle school, I slipped while running on hardwood floors in socks — the classic mistake. The result? A painful contusion on my knee. I couldn’t move it without sharp pain, and my parents and I feared the worst. We rushed to the ER, got X-rays, and were eventually told it wasn’t serious — just some rest, crutches, and a brace would do the trick.

The hospital bill? $3,000.

It was an expensive lesson: sometimes, what feels urgent might not be serious — but in the moment, there’s no easy way to know that.

Fast forward to last week, my friend was telling me about a Whoop report showing his HRV (Heart Rate Variability) was way off. He wasn’t sleeping — just lying awake for hours in bed — and his numbers looked abnormal. It made me wonder: what if this actually is something serious? What kind of help should he seek, and when?

That contrast — my unnecessary ER visit versus my friend’s subtle but possibly important signal — made me realize how inefficient and reactive our healthcare system is.

So I built this project.

I wanted to create a tool that empowers patients to better understand their symptoms before spending thousands or waiting days for a reply from a provider. A tool that bridges the gap between data (like biometrics) and context (like symptoms), and offers guidance without overloading the healthcare system.

This isn't just code. It's a response to real, lived inefficiencies — and my way of helping make healthcare more accessible, affordable, and informed for everyone.`,
    date: "2025-03-31",
  },
  {
    id: 4,
    title: "First post",
    excerpt: "Marketing Lessons: Nike",
    content: `Nike is exceptional at marketing. They partner with a ton of influencers and athletes. The swoosh lives without the name.

Nike has been around since 1964 and is one of the most recognizable brands. They spend a lot of time and money on legal fees to defend and protect their brand.

They grossed $51 billion last year. In a market with competitors like Puma, Adidas, Under Armor, North Face, Patagonia, Reebok, Eddie Bauer.

There are different product lines targeting different market segments: from ultra-expensive soccer cleats for high-performance athletes to lounge/leisurewear for everyday people.

A company’s mission reflects its long-term objectives. Goals can change, but the mission remains longer term.

A company’s portfolio must align with its objectives and goals to achieve its mission and succeed.`,
    date: "2025-01-15",
  },
  {
    id: 1,
    title: "Understanding Market Volatility",
    excerpt:
      "Exploring the factors that drive market fluctuations and strategies to navigate volatile periods.",
    content: `Market volatility is a natural part of investing...`,
    date: "2023-05-15",
  },
  {
    id: 2,
    title: "The Rise of ESG Investing",
    excerpt:
      "Analysis of how Environmental, Social, and Governance factors are reshaping investment strategies.",
    content: `ESG investing has become increasingly important...`,
    date: "2023-06-02",
  },
  {
    id: 3,
    title: "Cryptocurrency: A New Asset Class?",
    excerpt: "Examining the role of cryptocurrencies in modern investment portfolios.",
    content: `As cryptocurrencies continue to evolve...`,
    date: "2023-06-20",
  },
].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

export default function Blog() {
  const [expandedPost, setExpandedPost] = useState<number | null>(null);

  const togglePost = (id: number) => {
    setExpandedPost(expandedPost === id ? null : id);
  };

  return (
    <div className="min-h-screen flex flex-col">
      {/* Hero Section */}
      <section className="bg-gradient-to-r from-blue-600 to-cyan-600 py-16 text-white mb-12">
        <div className="container mx-auto px-4 text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">My Blog</h1>
          <p className="max-w-2xl mx-auto text-lg md:text-xl">
            Where I share insights about financial markets, technology trends, and the intersection
            of computer science and finance.
          </p>
        </div>
      </section>

      {/* Main Blog Content */}
      <div className="container mx-auto px-4 flex-grow">
        <div className="space-y-6">
          {blogPosts.map((post) => (
            <div
              key={post.id}
              className="bg-white border border-gray-200 rounded-lg shadow-sm overflow-hidden"
            >
              {/* Post Heading */}
              <div
                className="p-6 cursor-pointer hover:bg-gray-50 transition-colors"
                onClick={() => togglePost(post.id)}
              >
                <div className="flex justify-between items-start mb-2">
                  <h2 className="text-2xl font-semibold text-gray-900">{post.title}</h2>
                  <span className="text-gray-500 text-sm">{post.date}</span>
                </div>
                <p className="text-gray-700 mb-4">{post.excerpt}</p>
                <button className="text-blue-600 hover:text-blue-500 transition-colors">
                  {expandedPost === post.id ? "Show less" : "Read more"}
                </button>
              </div>
              {/* Expanded Content */}
              {expandedPost === post.id && (
                <div className="px-6 pb-6 border-t border-gray-200">
                  <div className="pt-4 prose max-w-none text-gray-700">
                    {post.content.split("\n").map((paragraph, index) => (
                      <p key={index} className="mb-4">
                        {paragraph}
                      </p>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
